### ISSUE TITLE
Error trying to connect, refreshing the regions list from database account and will retry the request.

### ISSUE THREAD

**Issue by DuffLV** [Winvision/vsts-tasks#11]
Hi, after figuring out how the connection string should look, I try to perform the creation of collection operation. The task gets stuck with the following message coming from the agent:

![image](https://user-images.githubusercontent.com/12030333/62298682-2323bd80-b47c-11e9-98b8-1c42d5c2819e.png)

any ideas?

**Comment by DuffLV** [comment]
An update on this - after a while, the following error is displayed:

2019-08-02T06:01:47.7963162Z { Error: connect ECONNREFUSED 127.0.0.1:443
2019-08-02T06:01:47.7965510Z     at Object.exports._errnoException (util.js:1018:11)
2019-08-02T06:01:47.7965609Z     at exports._exceptionWithHostPort (util.js:1041:20)
2019-08-02T06:01:47.7965956Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
2019-08-02T06:01:47.7966052Z   code: 'ECONNREFUSED',
2019-08-02T06:01:47.7966088Z   errno: 'ECONNREFUSED',
2019-08-02T06:01:47.7966125Z   syscall: 'connect',
2019-08-02T06:01:47.7966161Z   address: '127.0.0.1',
2019-08-02T06:01:47.7966196Z   port: 443 }
2019-08-02T06:01:47.8024092Z ##[warning]Database trans doesn't exist.

even though the Database listed in the last line of the output does exist.

**Comment by eNeRGy164** [comment]
Why does it try to connect to localhost?

**Comment by valentyn-bulakh** [comment]
Are this task still is under support or not?

**Comment by valentyn-bulakh** [comment]
@DuffLV, @eNeRGy164 Michaël Hompus Can you help with configuration?

**Comment by valentyn-bulakh** [comment]
@eNeRGy164 Can you help with config?

**Comment by eNeRGy164** [comment]
Hi @valentyn-bulakh, I'm not familiair with the component, I only responded to the issue by the author.

I'm not sure if somebody is still maintaining this task. I think you can ask @mlankamp or @ppluijten as they created the component.

**Comment by valentyn-bulakh** [comment]
@eNeRGy164 Thank you for your response.

 @mlankamp or @ppluijten can you help with task configuration?
